// Noms français des pays hôtes, indexés par le code à 3 lettres stocké en base
// pour les circuits (ISO 3166-1 alpha-3, avec quelques codes motorsport : GER, NED, SUI...)
export const COUNTRY_NAMES = {
  ARG: 'Argentine',
  AUS: 'Australie',
  AUT: 'Autriche',
  AZE: 'Azerbaïdjan',
  BEL: 'Belgique',
  BHR: 'Bahreïn',
  BRA: 'Brésil',
  CAN: 'Canada',
  CHN: 'Chine',
  ESP: 'Espagne',
  FRA: 'France',
  GBR: 'Royaume-Uni',
  GER: 'Allemagne',
  HUN: 'Hongrie',
  IND: 'Inde',
  ITA: 'Italie',
  JPN: 'Japon',
  KOR: 'Corée du Sud',
  MAR: 'Maroc',
  MEX: 'Mexique',
  MON: 'Monaco',
  MYS: 'Malaisie',
  NED: 'Pays-Bas',
  PRT: 'Portugal',
  QAT: 'Qatar',
  RUS: 'Russie',
  SAU: 'Arabie saoudite',
  SGP: 'Singapour',
  SUI: 'Suisse',
  SWE: 'Suède',
  TUR: 'Turquie',
  UAE: 'Émirats arabes unis',
  USA: 'États-Unis',
  ZAF: 'Afrique du Sud',
}
